name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:    
      matrix:
        arch: [64]

    steps:
    # Install dependencies
    - name: Install libck
      run: sudo apt-get install libck-dev    
    - name: Install Cyclone
      run: |
        wget https://github.com/cyclone-scheme/binary-releases/raw/master/ubuntu-18.04-lts/cyclone-scheme_0.22_amd64.deb 
        sudo apt install ./cyclone-scheme_0.22_amd64.deb
      
    # Setup winds
    - uses: actions/checkout@v2
    - name: Build
      run: make
    #- name: Install
    #  run: sudo make install
      
    # Run our tests
    - name: Run tests
      run: |
        make test
    
